package com.app.dhsloader.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * @author Ram
 * 
 */
@Entity
@Table(name = "XREF_XX_DSP")
public class XrefXxDsp implements java.io.Serializable {

	private static final long serialVersionUID = -1636443729844129372L;
	private XrefXxDspId id;

	public XrefXxDsp() {
	}

	public XrefXxDsp(XrefXxDspId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "action", column = @Column(name = "ACTION", length = 50)),
			@AttributeOverride(name = "levelcode", column = @Column(name = "LEVELCODE", length = 50)),
			@AttributeOverride(name = "ipc", column = @Column(name = "IPC", length = 50)), @AttributeOverride(name = "quoteid", column = @Column(name = "QUOTEID", length = 50)),
			@AttributeOverride(name = "ric", column = @Column(name = "RIC", length = 50)), @AttributeOverride(name = "sedol", column = @Column(name = "SEDOL", length = 50)),
			@AttributeOverride(name = "issuepermid", column = @Column(name = "ISSUEPERMID", length = 50)),
			@AttributeOverride(name = "assetid", column = @Column(name = "ASSETID", length = 50)), @AttributeOverride(name = "pilc", column = @Column(name = "PILC", length = 50)),
			@AttributeOverride(name = "cusip", column = @Column(name = "CUSIP", length = 50)),
			@AttributeOverride(name = "orgpermid", column = @Column(name = "ORGPERMID", length = 50)),
			@AttributeOverride(name = "assetstatus", column = @Column(name = "ASSETSTATUS", length = 50)),
			@AttributeOverride(name = "assetstatuscf", column = @Column(name = "ASSETSTATUSCF", length = 50)),
			@AttributeOverride(name = "assetstatusp", column = @Column(name = "ASSETSTATUSP", length = 50)),
			@AttributeOverride(name = "basketundisinlist", column = @Column(name = "BASKETUNDISINLIST", length = 50)),
			@AttributeOverride(name = "basketundisinlistcf", column = @Column(name = "BASKETUNDISINLISTCF", length = 50)),
			@AttributeOverride(name = "basketundisinlistp", column = @Column(name = "BASKETUNDISINLISTP", length = 50)),
			@AttributeOverride(name = "basketwrrindicator", column = @Column(name = "BASKETWRRINDICATOR", length = 50)),
			@AttributeOverride(name = "basketwrrindicatorcf", column = @Column(name = "BASKETWRRINDICATORCF", length = 50)),
			@AttributeOverride(name = "basketwrrindicatorp", column = @Column(name = "BASKETWRRINDICATORP", length = 50)),
			@AttributeOverride(name = "cficode", column = @Column(name = "CFICODE", length = 50)),
			@AttributeOverride(name = "cficodecf", column = @Column(name = "CFICODECF", length = 50)),
			@AttributeOverride(name = "cficodep", column = @Column(name = "CFICODEP", length = 50)),
			@AttributeOverride(name = "cincode", column = @Column(name = "CINCODE", length = 50)),
			@AttributeOverride(name = "cincodecf", column = @Column(name = "CINCODECF", length = 50)),
			@AttributeOverride(name = "cincodep", column = @Column(name = "CINCODEP", length = 50)),
			@AttributeOverride(name = "complegaldomicile", column = @Column(name = "COMPLEGALDOMICILE", length = 50)),
			@AttributeOverride(name = "complegaldomicilecf", column = @Column(name = "COMPLEGALDOMICILECF", length = 50)),
			@AttributeOverride(name = "complegaldomicilep", column = @Column(name = "COMPLEGALDOMICILEP", length = 50)),
			@AttributeOverride(name = "compshortname", column = @Column(name = "COMPSHORTNAME", length = 50)),
			@AttributeOverride(name = "compshortnamecf", column = @Column(name = "COMPSHORTNAMECF", length = 50)),
			@AttributeOverride(name = "compshortnamep", column = @Column(name = "COMPSHORTNAMEP", length = 50)),
			@AttributeOverride(name = "dealstartdate", column = @Column(name = "DEALSTARTDATE", length = 50)),
			@AttributeOverride(name = "dealstartdatecf", column = @Column(name = "DEALSTARTDATECF", length = 50)),
			@AttributeOverride(name = "dealstartdatep", column = @Column(name = "DEALSTARTDATEP", length = 50)),
			@AttributeOverride(name = "eeavenueelflg", column = @Column(name = "EEAVENUEELFLG", length = 50)),
			@AttributeOverride(name = "eeavenueelflgcf", column = @Column(name = "EEAVENUEELFLGCF", length = 50)),
			@AttributeOverride(name = "eeavenueelflgp", column = @Column(name = "EEAVENUEELFLGP", length = 50)),
			@AttributeOverride(name = "fininsshname", column = @Column(name = "FININSSHNAME", length = 50)),
			@AttributeOverride(name = "fininsshnamecf", column = @Column(name = "FININSSHNAMECF", length = 50)),
			@AttributeOverride(name = "fininsshnamep", column = @Column(name = "FININSSHNAMEP", length = 50)),
			@AttributeOverride(name = "fininsshnameesma", column = @Column(name = "FININSSHNAMEESMA", length = 50)),
			@AttributeOverride(name = "fininsshnameesmacf", column = @Column(name = "FININSSHNAMEESMACF", length = 50)),
			@AttributeOverride(name = "fininsshnameesmap", column = @Column(name = "FININSSHNAMEESMAP", length = 50)),
			@AttributeOverride(name = "inesmafirds", column = @Column(name = "INESMAFIRDS", length = 50)),
			@AttributeOverride(name = "inesmafirdscf", column = @Column(name = "INESMAFIRDSCF", length = 50)),
			@AttributeOverride(name = "inesmafirdsp", column = @Column(name = "INESMAFIRDSP", length = 50)),
			@AttributeOverride(name = "insclassesma", column = @Column(name = "INSCLASSESMA", length = 50)),
			@AttributeOverride(name = "insclassesmacf", column = @Column(name = "INSCLASSESMACF", length = 50)),
			@AttributeOverride(name = "insclassesmap", column = @Column(name = "INSCLASSESMAP", length = 50)),
			@AttributeOverride(name = "insfullnameesma", column = @Column(name = "INSFULLNAMEESMA", length = 50)),
			@AttributeOverride(name = "insfullnameesmacf", column = @Column(name = "INSFULLNAMEESMACF", length = 50)),
			@AttributeOverride(name = "insfullnameesmap", column = @Column(name = "INSFULLNAMEESMAP", length = 50)),
			@AttributeOverride(name = "isin", column = @Column(name = "ISIN", length = 50)), @AttributeOverride(name = "isincf", column = @Column(name = "ISINCF", length = 50)),
			@AttributeOverride(name = "isinp", column = @Column(name = "ISINP", length = 50)),
			@AttributeOverride(name = "issuedate", column = @Column(name = "ISSUEDATE", length = 50)),
			@AttributeOverride(name = "issuedatecf", column = @Column(name = "ISSUEDATECF", length = 50)),
			@AttributeOverride(name = "issuedatep", column = @Column(name = "ISSUEDATEP", length = 50)),
			@AttributeOverride(name = "issuerlei", column = @Column(name = "ISSUERLEI", length = 50)),
			@AttributeOverride(name = "issuerleicf", column = @Column(name = "ISSUERLEICF", length = 50)),
			@AttributeOverride(name = "issuerleip", column = @Column(name = "ISSUERLEIP", length = 50)),
			@AttributeOverride(name = "issortrvenueleiesma", column = @Column(name = "ISSORTRVENUELEIESMA", length = 50)),
			@AttributeOverride(name = "issortrvenueleiesmacf", column = @Column(name = "ISSORTRVENUELEIESMACF", length = 50)),
			@AttributeOverride(name = "issortrvenueleiesmap", column = @Column(name = "ISSORTRVENUELEIESMAP", length = 50)),
			@AttributeOverride(name = "mrkattsrcpermid", column = @Column(name = "MRKATTSRCPERMID", length = 50)),
			@AttributeOverride(name = "mrkattsrcpermidcf", column = @Column(name = "MRKATTSRCPERMIDCF", length = 50)),
			@AttributeOverride(name = "mrkattsrcpermidp", column = @Column(name = "MRKATTSRCPERMIDP", length = 50)),
			@AttributeOverride(name = "marketmic", column = @Column(name = "MARKETMIC", length = 50)),
			@AttributeOverride(name = "marketmiccf", column = @Column(name = "MARKETMICCF", length = 50)),
			@AttributeOverride(name = "marketmicp", column = @Column(name = "MARKETMICP", length = 50)),
			@AttributeOverride(name = "maturitydate", column = @Column(name = "MATURITYDATE", length = 50)),
			@AttributeOverride(name = "maturitydatecf", column = @Column(name = "MATURITYDATECF", length = 50)),
			@AttributeOverride(name = "maturitydatep", column = @Column(name = "MATURITYDATEP", length = 50)),
			@AttributeOverride(name = "mifidasclofun", column = @Column(name = "MIFIDASCLOFUN", length = 50)),
			@AttributeOverride(name = "mifidasclofuncf", column = @Column(name = "MIFIDASCLOFUNCF", length = 50)),
			@AttributeOverride(name = "mifidasclofunp", column = @Column(name = "MIFIDASCLOFUNP", length = 50)),
			@AttributeOverride(name = "mifidadnapinsesma", column = @Column(name = "MIFIDADNAPINSESMA", length = 50)),
			@AttributeOverride(name = "mifidadnapinsesmacf", column = @Column(name = "MIFIDADNAPINSESMACF", length = 50)),
			@AttributeOverride(name = "mifidadnapinsesmap", column = @Column(name = "MIFIDADNAPINSESMAP", length = 50)),
			@AttributeOverride(name = "mifidadnoftpinsesma", column = @Column(name = "MIFIDADNOFTPINSESMA", length = 50)),
			@AttributeOverride(name = "mifidadnoftpinsesmacf", column = @Column(name = "MIFIDADNOFTPINSESMACF", length = 50)),
			@AttributeOverride(name = "mifidadnoftpinsesmap", column = @Column(name = "MIFIDADNOFTPINSESMAP", length = 50)),
			@AttributeOverride(name = "mifidavdatuesma", column = @Column(name = "MIFIDAVDATUESMA", length = 50)),
			@AttributeOverride(name = "mifidavdatuesmacf", column = @Column(name = "MIFIDAVDATUESMACF", length = 50)),
			@AttributeOverride(name = "mifidavdatuesmap", column = @Column(name = "MIFIDAVDATUESMAP", length = 50)),
			@AttributeOverride(name = "mifidavdatucurcode", column = @Column(name = "MIFIDAVDATUCURCODE", length = 50)),
			@AttributeOverride(name = "mifidavdatucurcodecf", column = @Column(name = "MIFIDAVDATUCURCODECF", length = 50)),
			@AttributeOverride(name = "mifidavdatucurcodep", column = @Column(name = "MIFIDAVDATUCURCODEP", length = 50)),
			@AttributeOverride(name = "mifidavvaoftresma", column = @Column(name = "MIFIDAVVAOFTRESMA", length = 50)),
			@AttributeOverride(name = "mifidavvaoftresmacf", column = @Column(name = "MIFIDAVVAOFTRESMACF", length = 50)),
			@AttributeOverride(name = "mifidavvaoftresmap", column = @Column(name = "MIFIDAVVAOFTRESMAP", length = 50)),
			@AttributeOverride(name = "mifidavvaoftrcurcode", column = @Column(name = "MIFIDAVVAOFTRCURCODE", length = 50)),
			@AttributeOverride(name = "mifidavvaoftrcurcodecf", column = @Column(name = "MIFIDAVVAOFTRCURCODECF", length = 50)),
			@AttributeOverride(name = "mifidavvaoftrcurcodep", column = @Column(name = "MIFIDAVVAOFTRCURCODEP", length = 50)),
			@AttributeOverride(name = "mifidbaseprod", column = @Column(name = "MIFIDBASEPROD", length = 50)),
			@AttributeOverride(name = "mifidbaseprodcf", column = @Column(name = "MIFIDBASEPRODCF", length = 50)),
			@AttributeOverride(name = "mifidbaseprodp", column = @Column(name = "MIFIDBASEPRODP", length = 50)),
			@AttributeOverride(name = "mifidbaseprodesma", column = @Column(name = "MIFIDBASEPRODESMA", length = 50)),
			@AttributeOverride(name = "mifidbaseprodesmacf", column = @Column(name = "MIFIDBASEPRODESMACF", length = 50)),
			@AttributeOverride(name = "mifidbaseprodesmap", column = @Column(name = "MIFIDBASEPRODESMAP", length = 50)),
			@AttributeOverride(name = "mifidbondseni", column = @Column(name = "MIFIDBONDSENI", length = 50)),
			@AttributeOverride(name = "mifidbondsenicf", column = @Column(name = "MIFIDBONDSENICF", length = 50)),
			@AttributeOverride(name = "mifidbondsenip", column = @Column(name = "MIFIDBONDSENIP", length = 50)),
			@AttributeOverride(name = "mifidbondtype", column = @Column(name = "MIFIDBONDTYPE", length = 50)),
			@AttributeOverride(name = "mifidbondtypecf", column = @Column(name = "MIFIDBONDTYPECF", length = 50)),
			@AttributeOverride(name = "mifidbondtypep", column = @Column(name = "MIFIDBONDTYPEP", length = 50)),
			@AttributeOverride(name = "mifidclobflag", column = @Column(name = "MIFIDCLOBFLAG", length = 50)),
			@AttributeOverride(name = "mifidclobflagcf", column = @Column(name = "MIFIDCLOBFLAGCF", length = 50)),
			@AttributeOverride(name = "mifidclobflagp", column = @Column(name = "MIFIDCLOBFLAGP", length = 50)),
			@AttributeOverride(name = "mifidcofialiinfornewbo", column = @Column(name = "MIFIDCOFIALIINFORNEWBO", length = 50)),
			@AttributeOverride(name = "mifidcofialiinfornewbocf", column = @Column(name = "MIFIDCOFIALIINFORNEWBOCF", length = 50)),
			@AttributeOverride(name = "mifidcofialiinfornewbop", column = @Column(name = "MIFIDCOFIALIINFORNEWBOP", length = 50)),
			@AttributeOverride(name = "mifidcodein", column = @Column(name = "MIFIDCODEIN", length = 50)),
			@AttributeOverride(name = "mifidcodeincf", column = @Column(name = "MIFIDCODEINCF", length = 50)),
			@AttributeOverride(name = "mifidcodeinp", column = @Column(name = "MIFIDCODEINP", length = 50)),
			@AttributeOverride(name = "mifidcodeinesma", column = @Column(name = "MIFIDCODEINESMA", length = 50)),
			@AttributeOverride(name = "mifidcodeinesmacf", column = @Column(name = "MIFIDCODEINESMACF", length = 50)),
			@AttributeOverride(name = "mifidcodeinesmap", column = @Column(name = "MIFIDCODEINESMAP", length = 50)),
			@AttributeOverride(name = "mifidcoinflesma", column = @Column(name = "MIFIDCOINFLESMA", length = 50)),
			@AttributeOverride(name = "mifidcoinflesmacf", column = @Column(name = "MIFIDCOINFLESMACF", length = 50)),
			@AttributeOverride(name = "mifidcoinflesmap", column = @Column(name = "MIFIDCOINFLESMAP", length = 50)),
			@AttributeOverride(name = "mifidcoinre", column = @Column(name = "MIFIDCOINRE", length = 50)),
			@AttributeOverride(name = "mifidcoinrecf", column = @Column(name = "MIFIDCOINRECF", length = 50)),
			@AttributeOverride(name = "mifidcoinrep", column = @Column(name = "MIFIDCOINREP", length = 50)),
			@AttributeOverride(name = "mifidcotype", column = @Column(name = "MIFIDCOTYPE", length = 50)),
			@AttributeOverride(name = "mifidcotypecf", column = @Column(name = "MIFIDCOTYPECF", length = 50)),
			@AttributeOverride(name = "mifidcotypep", column = @Column(name = "MIFIDCOTYPEP", length = 50)),
			@AttributeOverride(name = "mifiddeltypeesma", column = @Column(name = "MIFIDDELTYPEESMA", length = 50)),
			@AttributeOverride(name = "mifiddeltypeesmacf", column = @Column(name = "MIFIDDELTYPEESMACF", length = 50)),
			@AttributeOverride(name = "mifiddeltypeesmap", column = @Column(name = "MIFIDDELTYPEESMAP", length = 50)),
			@AttributeOverride(name = "mifidemalsubtype", column = @Column(name = "MIFIDEMALSUBTYPE", length = 50)),
			@AttributeOverride(name = "mifidemalsubtypecf", column = @Column(name = "MIFIDEMALSUBTYPECF", length = 50)),
			@AttributeOverride(name = "mifidemalsubtypep", column = @Column(name = "MIFIDEMALSUBTYPEP", length = 50)),
			@AttributeOverride(name = "mifidexerstyle", column = @Column(name = "MIFIDEXERSTYLE", length = 50)),
			@AttributeOverride(name = "mifidexerstylecf", column = @Column(name = "MIFIDEXERSTYLECF", length = 50)),
			@AttributeOverride(name = "mifidexerstylep", column = @Column(name = "MIFIDEXERSTYLEP", length = 50)),
			@AttributeOverride(name = "mifidexerstyleesma", column = @Column(name = "MIFIDEXERSTYLEESMA", length = 50)),
			@AttributeOverride(name = "mifidexerstyleesmacf", column = @Column(name = "MIFIDEXERSTYLEESMACF", length = 50)),
			@AttributeOverride(name = "mifidexerstyleesmap", column = @Column(name = "MIFIDEXERSTYLEESMAP", length = 50)),
			@AttributeOverride(name = "mifidexpdateesma", column = @Column(name = "MIFIDEXPDATEESMA", length = 50)),
			@AttributeOverride(name = "mifidexpdateesmacf", column = @Column(name = "MIFIDEXPDATEESMACF", length = 50)),
			@AttributeOverride(name = "mifidexpdateesmap", column = @Column(name = "MIFIDEXPDATEESMAP", length = 50)),
			@AttributeOverride(name = "mifidfiprtype", column = @Column(name = "MIFIDFIPRTYPE", length = 50)),
			@AttributeOverride(name = "mifidfiprtypecf", column = @Column(name = "MIFIDFIPRTYPECF", length = 50)),
			@AttributeOverride(name = "mifidfiprtypep", column = @Column(name = "MIFIDFIPRTYPEP", length = 50)),
			@AttributeOverride(name = "mifidfiprtypeesma", column = @Column(name = "MIFIDFIPRTYPEESMA", length = 50)),
			@AttributeOverride(name = "mifidfiprtypeesmacf", column = @Column(name = "MIFIDFIPRTYPEESMACF", length = 50)),
			@AttributeOverride(name = "mifidfiprtypeesmap", column = @Column(name = "MIFIDFIPRTYPEESMAP", length = 50)),
			@AttributeOverride(name = "mifidfrtradedate", column = @Column(name = "MIFIDFRTRADEDATE", length = 50)),
			@AttributeOverride(name = "mifidfrtradedatecf", column = @Column(name = "MIFIDFRTRADEDATECF", length = 50)),
			@AttributeOverride(name = "mifidfrtradedatep", column = @Column(name = "MIFIDFRTRADEDATEP", length = 50)),
			@AttributeOverride(name = "mifidfrtradedateesma", column = @Column(name = "MIFIDFRTRADEDATEESMA", length = 50)),
			@AttributeOverride(name = "mifidfrtradedateesmacf", column = @Column(name = "MIFIDFRTRADEDATEESMACF", length = 50)),
			@AttributeOverride(name = "mifidfrtradedateesmap", column = @Column(name = "MIFIDFRTRADEDATEESMAP", length = 50)),
			@AttributeOverride(name = "mifidflag", column = @Column(name = "MIFIDFLAG", length = 50)),
			@AttributeOverride(name = "mifidflagcf", column = @Column(name = "MIFIDFLAGCF", length = 50)),
			@AttributeOverride(name = "mifidflagp", column = @Column(name = "MIFIDFLAGP", length = 50)),
			@AttributeOverride(name = "mifidfrfloatesma", column = @Column(name = "MIFIDFRFLOATESMA", length = 50)),
			@AttributeOverride(name = "mifidfrfloatesmacf", column = @Column(name = "MIFIDFRFLOATESMACF", length = 50)),
			@AttributeOverride(name = "mifidfrfloatesmap", column = @Column(name = "MIFIDFRFLOATESMAP", length = 50)),
			@AttributeOverride(name = "mifidfrfloatcurcode", column = @Column(name = "MIFIDFRFLOATCURCODE", length = 50)),
			@AttributeOverride(name = "mifidfrfloatcurcodecf", column = @Column(name = "MIFIDFRFLOATCURCODECF", length = 50)),
			@AttributeOverride(name = "mifidfrfloatcurcodep", column = @Column(name = "MIFIDFRFLOATCURCODEP", length = 50)),
			@AttributeOverride(name = "mifidfusubpr", column = @Column(name = "MIFIDFUSUBPR", length = 50)),
			@AttributeOverride(name = "mifidfusubprcf", column = @Column(name = "MIFIDFUSUBPRCF", length = 50)),
			@AttributeOverride(name = "mifidfusubprp", column = @Column(name = "MIFIDFUSUBPRP", length = 50)),
			@AttributeOverride(name = "mifidfusubpresma", column = @Column(name = "MIFIDFUSUBPRESMA", length = 50)),
			@AttributeOverride(name = "mifidfusubpresmacf", column = @Column(name = "MIFIDFUSUBPRESMACF", length = 50)),
			@AttributeOverride(name = "mifidfusubpresmap", column = @Column(name = "MIFIDFUSUBPRESMAP", length = 50)),
			@AttributeOverride(name = "mifidissdateesma", column = @Column(name = "MIFIDISSDATEESMA", length = 50)),
			@AttributeOverride(name = "mifidissdateesmacf", column = @Column(name = "MIFIDISSDATEESMACF", length = 50)),
			@AttributeOverride(name = "mifidissdateesmap", column = @Column(name = "MIFIDISSDATEESMAP", length = 50)),
			@AttributeOverride(name = "mifidisssizeesma", column = @Column(name = "MIFIDISSSIZEESMA", length = 50)),
			@AttributeOverride(name = "mifidisssizeesmacf", column = @Column(name = "MIFIDISSSIZEESMACF", length = 50)),
			@AttributeOverride(name = "mifidisssizeesmap", column = @Column(name = "MIFIDISSSIZEESMAP", length = 50)),
			@AttributeOverride(name = "mifidmatdate", column = @Column(name = "MIFIDMATDATE", length = 50)),
			@AttributeOverride(name = "mifidmatdatecf", column = @Column(name = "MIFIDMATDATECF", length = 50)),
			@AttributeOverride(name = "mifidmatdatep", column = @Column(name = "MIFIDMATDATEP", length = 50)),
			@AttributeOverride(name = "mifidmatdateesma", column = @Column(name = "MIFIDMATDATEESMA", length = 50)),
			@AttributeOverride(name = "mifidmatdateesmacf", column = @Column(name = "MIFIDMATDATEESMACF", length = 50)),
			@AttributeOverride(name = "mifidmatdateesmap", column = @Column(name = "MIFIDMATDATEESMAP", length = 50)),
			@AttributeOverride(name = "mifidmostremaesma", column = @Column(name = "MIFIDMOSTREMAESMA", length = 50)),
			@AttributeOverride(name = "mifidmostremaesmacf", column = @Column(name = "MIFIDMOSTREMAESMACF", length = 50)),
			@AttributeOverride(name = "mifidmostremaesmap", column = @Column(name = "MIFIDMOSTREMAESMAP", length = 50)),
			@AttributeOverride(name = "mifidoptype", column = @Column(name = "MIFIDOPTYPE", length = 50)),
			@AttributeOverride(name = "mifidoptypecf", column = @Column(name = "MIFIDOPTYPECF", length = 50)),
			@AttributeOverride(name = "mifidoptypep", column = @Column(name = "MIFIDOPTYPEP", length = 50)),
			@AttributeOverride(name = "mifidoptypeesma", column = @Column(name = "MIFIDOPTYPEESMA", length = 50)),
			@AttributeOverride(name = "mifidoptypeesmacf", column = @Column(name = "MIFIDOPTYPEESMACF", length = 50)),
			@AttributeOverride(name = "mifidoptypeesmap", column = @Column(name = "MIFIDOPTYPEESMAP", length = 50)),
			@AttributeOverride(name = "mifidptuw12esma", column = @Column(name = "MIFIDPTUW12ESMA", length = 50)),
			@AttributeOverride(name = "mifidptuw12esmacf", column = @Column(name = "MIFIDPTUW12ESMACF", length = 50)),
			@AttributeOverride(name = "mifidptuw12esmap", column = @Column(name = "MIFIDPTUW12ESMAP", length = 50)),
			@AttributeOverride(name = "mifidptuwptv12mesma", column = @Column(name = "MIFIDPTUWPTV12MESMA", length = 50)),
			@AttributeOverride(name = "mifidptuwptv12mesmacf", column = @Column(name = "MIFIDPTUWPTV12MESMACF", length = 50)),
			@AttributeOverride(name = "mifidptuwptv12mesmap", column = @Column(name = "MIFIDPTUWPTV12MESMAP", length = 50)),
			@AttributeOverride(name = "mifidpotrlisthfl", column = @Column(name = "MIFIDPOTRLISTHFL", length = 50)),
			@AttributeOverride(name = "mifidpotrlisthflcf", column = @Column(name = "MIFIDPOTRLISTHFLCF", length = 50)),
			@AttributeOverride(name = "mifidpotrlisthflp", column = @Column(name = "MIFIDPOTRLISTHFLP", length = 50)),
			@AttributeOverride(name = "mifidpotrlisthvl", column = @Column(name = "MIFIDPOTRLISTHVL", length = 50)),
			@AttributeOverride(name = "mifidpotrlisthvlcf", column = @Column(name = "MIFIDPOTRLISTHVLCF", length = 50)),
			@AttributeOverride(name = "mifidpotrlisthvlp", column = @Column(name = "MIFIDPOTRLISTHVLP", length = 50)),
			@AttributeOverride(name = "mifidpotrlistrper", column = @Column(name = "MIFIDPOTRLISTRPER", length = 50)),
			@AttributeOverride(name = "mifidpotrlistrpercf", column = @Column(name = "MIFIDPOTRLISTRPERCF", length = 50)),
			@AttributeOverride(name = "mifidpotrlistrperp", column = @Column(name = "MIFIDPOTRLISTRPERP", length = 50)),
			@AttributeOverride(name = "mifidpotrlisvoper", column = @Column(name = "MIFIDPOTRLISVOPER", length = 50)),
			@AttributeOverride(name = "mifidpotrlisvopercf", column = @Column(name = "MIFIDPOTRLISVOPERCF", length = 50)),
			@AttributeOverride(name = "mifidpotrlisvoperp", column = @Column(name = "MIFIDPOTRLISVOPERP", length = 50)),
			@AttributeOverride(name = "mifidpotrsstithfl", column = @Column(name = "MIFIDPOTRSSTITHFL", length = 50)),
			@AttributeOverride(name = "mifidpotrsstithflcf", column = @Column(name = "MIFIDPOTRSSTITHFLCF", length = 50)),
			@AttributeOverride(name = "mifidpotrsstithflp", column = @Column(name = "MIFIDPOTRSSTITHFLP", length = 50)),
			@AttributeOverride(name = "mifidpotrsstithvl", column = @Column(name = "MIFIDPOTRSSTITHVL", length = 50)),
			@AttributeOverride(name = "mifidpotrsstithvlcf", column = @Column(name = "MIFIDPOTRSSTITHVLCF", length = 50)),
			@AttributeOverride(name = "mifidpotrsstithvlp", column = @Column(name = "MIFIDPOTRSSTITHVLP", length = 50)),
			@AttributeOverride(name = "mifidpotrsstitrper", column = @Column(name = "MIFIDPOTRSSTITRPER", length = 50)),
			@AttributeOverride(name = "mifidpotrsstitrpercf", column = @Column(name = "MIFIDPOTRSSTITRPERCF", length = 50)),
			@AttributeOverride(name = "mifidpotrsstitrperp", column = @Column(name = "MIFIDPOTRSSTITRPERP", length = 50)),
			@AttributeOverride(name = "mifidpotrsstivoper", column = @Column(name = "MIFIDPOTRSSTIVOPER", length = 50)),
			@AttributeOverride(name = "mifidpotrsstivopercf", column = @Column(name = "MIFIDPOTRSSTIVOPERCF", length = 50)),
			@AttributeOverride(name = "mifidpotrsstivoperp", column = @Column(name = "MIFIDPOTRSSTIVOPERP", length = 50)),
			@AttributeOverride(name = "mifidpretrlisthfl", column = @Column(name = "MIFIDPRETRLISTHFL", length = 50)),
			@AttributeOverride(name = "mifidpretrlisthflcf", column = @Column(name = "MIFIDPRETRLISTHFLCF", length = 50)),
			@AttributeOverride(name = "mifidpretrlisthflp", column = @Column(name = "MIFIDPRETRLISTHFLP", length = 50)),
			@AttributeOverride(name = "mifidpretrlisthvl", column = @Column(name = "MIFIDPRETRLISTHVL", length = 50)),
			@AttributeOverride(name = "mifidpretrlisthvlcf", column = @Column(name = "MIFIDPRETRLISTHVLCF", length = 50)),
			@AttributeOverride(name = "mifidpretrlisthvlp", column = @Column(name = "MIFIDPRETRLISTHVLP", length = 50)),
			@AttributeOverride(name = "mifidpretrlistrper", column = @Column(name = "MIFIDPRETRLISTRPER", length = 50)),
			@AttributeOverride(name = "mifidpretrlistrpercf", column = @Column(name = "MIFIDPRETRLISTRPERCF", length = 50)),
			@AttributeOverride(name = "mifidpretrlistrperp", column = @Column(name = "MIFIDPRETRLISTRPERP", length = 50)),
			@AttributeOverride(name = "mifidpretrsstithfl", column = @Column(name = "MIFIDPRETRSSTITHFL", length = 50)),
			@AttributeOverride(name = "mifidpretrsstithflcf", column = @Column(name = "MIFIDPRETRSSTITHFLCF", length = 50)),
			@AttributeOverride(name = "mifidpretrsstithflp", column = @Column(name = "MIFIDPRETRSSTITHFLP", length = 50)),
			@AttributeOverride(name = "mifidpretrsstithvl", column = @Column(name = "MIFIDPRETRSSTITHVL", length = 50)),
			@AttributeOverride(name = "mifidpretrsstithvlcf", column = @Column(name = "MIFIDPRETRSSTITHVLCF", length = 50)),
			@AttributeOverride(name = "mifidpretrsstithvlp", column = @Column(name = "MIFIDPRETRSSTITHVLP", length = 50)),
			@AttributeOverride(name = "mifidpretrsstitrper", column = @Column(name = "MIFIDPRETRSSTITRPER", length = 50)),
			@AttributeOverride(name = "mifidpretrsstitrpercf", column = @Column(name = "MIFIDPRETRSSTITRPERCF", length = 50)),
			@AttributeOverride(name = "mifidpretrsstitrperp", column = @Column(name = "MIFIDPRETRSSTITRPERP", length = 50)),
			@AttributeOverride(name = "mifidregulatedesma", column = @Column(name = "MIFIDREGULATEDESMA", length = 50)),
			@AttributeOverride(name = "mifidregulatedesmacf", column = @Column(name = "MIFIDREGULATEDESMACF", length = 50)),
			@AttributeOverride(name = "mifidregulatedesmap", column = @Column(name = "MIFIDREGULATEDESMAP", length = 50)),
			@AttributeOverride(name = "mifidstmasizeesma", column = @Column(name = "MIFIDSTMASIZEESMA", length = 50)),
			@AttributeOverride(name = "mifidstmasizeesmacf", column = @Column(name = "MIFIDSTMASIZEESMACF", length = 50)),
			@AttributeOverride(name = "mifidstmasizeesmap", column = @Column(name = "MIFIDSTMASIZEESMAP", length = 50)),
			@AttributeOverride(name = "mifidstmasizecurcode", column = @Column(name = "MIFIDSTMASIZECURCODE", length = 50)),
			@AttributeOverride(name = "mifidstmasizecurcodecf", column = @Column(name = "MIFIDSTMASIZECURCODECF", length = 50)),
			@AttributeOverride(name = "mifidstmasizecurcodep", column = @Column(name = "MIFIDSTMASIZECURCODEP", length = 50)),
			@AttributeOverride(name = "mifidsubprod", column = @Column(name = "MIFIDSUBPROD", length = 50)),
			@AttributeOverride(name = "mifidsubprodcf", column = @Column(name = "MIFIDSUBPRODCF", length = 50)),
			@AttributeOverride(name = "mifidsubprodp", column = @Column(name = "MIFIDSUBPRODP", length = 50)),
			@AttributeOverride(name = "mifidsubprodesma", column = @Column(name = "MIFIDSUBPRODESMA", length = 50)),
			@AttributeOverride(name = "mifidsubprodesmacf", column = @Column(name = "MIFIDSUBPRODESMACF", length = 50)),
			@AttributeOverride(name = "mifidsubprodesmap", column = @Column(name = "MIFIDSUBPRODESMAP", length = 50)),
			@AttributeOverride(name = "mifidtermdate", column = @Column(name = "MIFIDTERMDATE", length = 50)),
			@AttributeOverride(name = "mifidtermdatecf", column = @Column(name = "MIFIDTERMDATECF", length = 50)),
			@AttributeOverride(name = "mifidtermdatep", column = @Column(name = "MIFIDTERMDATEP", length = 50)),
			@AttributeOverride(name = "mifidtermdateesma", column = @Column(name = "MIFIDTERMDATEESMA", length = 50)),
			@AttributeOverride(name = "mifidtermdateesmacf", column = @Column(name = "MIFIDTERMDATEESMACF", length = 50)),
			@AttributeOverride(name = "mifidtermdateesmap", column = @Column(name = "MIFIDTERMDATEESMAP", length = 50)),
			@AttributeOverride(name = "mifidtrobflag", column = @Column(name = "MIFIDTROBFLAG", length = 50)),
			@AttributeOverride(name = "mifidtrobflagcf", column = @Column(name = "MIFIDTROBFLAGCF", length = 50)),
			@AttributeOverride(name = "mifidtrobflagp", column = @Column(name = "MIFIDTROBFLAGP", length = 50)),
			@AttributeOverride(name = "mifidtradapdate", column = @Column(name = "MIFIDTRADAPDATE", length = 50)),
			@AttributeOverride(name = "mifidtradapdatecf", column = @Column(name = "MIFIDTRADAPDATECF", length = 50)),
			@AttributeOverride(name = "mifidtradapdatep", column = @Column(name = "MIFIDTRADAPDATEP", length = 50)),
			@AttributeOverride(name = "mifidtradapdateesma", column = @Column(name = "MIFIDTRADAPDATEESMA", length = 50)),
			@AttributeOverride(name = "mifidtradapdateesmacf", column = @Column(name = "MIFIDTRADAPDATEESMACF", length = 50)),
			@AttributeOverride(name = "mifidtradapdateesmap", column = @Column(name = "MIFIDTRADAPDATEESMAP", length = 50)),
			@AttributeOverride(name = "mifidtradreqdate", column = @Column(name = "MIFIDTRADREQDATE", length = 50)),
			@AttributeOverride(name = "mifidtradreqdatecf", column = @Column(name = "MIFIDTRADREQDATECF", length = 50)),
			@AttributeOverride(name = "mifidtradreqdatep", column = @Column(name = "MIFIDTRADREQDATEP", length = 50)),
			@AttributeOverride(name = "mifidtradreqdateesma", column = @Column(name = "MIFIDTRADREQDATEESMA", length = 50)),
			@AttributeOverride(name = "mifidtradreqdateesmacf", column = @Column(name = "MIFIDTRADREQDATEESMACF", length = 50)),
			@AttributeOverride(name = "mifidtradreqdateesmap", column = @Column(name = "MIFIDTRADREQDATEESMAP", length = 50)),
			@AttributeOverride(name = "mifidtrtype", column = @Column(name = "MIFIDTRTYPE", length = 50)),
			@AttributeOverride(name = "mifidtrtypecf", column = @Column(name = "MIFIDTRTYPECF", length = 50)),
			@AttributeOverride(name = "mifidtrtypep", column = @Column(name = "MIFIDTRTYPEP", length = 50)),
			@AttributeOverride(name = "mifidtrtypeesma", column = @Column(name = "MIFIDTRTYPEESMA", length = 50)),
			@AttributeOverride(name = "mifidtrtypeesmacf", column = @Column(name = "MIFIDTRTYPEESMACF", length = 50)),
			@AttributeOverride(name = "mifidtrtypeesmap", column = @Column(name = "MIFIDTRTYPEESMAP", length = 50)),
			@AttributeOverride(name = "mifidundindname", column = @Column(name = "MIFIDUNDINDNAME", length = 50)),
			@AttributeOverride(name = "mifidundindnamecf", column = @Column(name = "MIFIDUNDINDNAMECF", length = 50)),
			@AttributeOverride(name = "mifidundindnamep", column = @Column(name = "MIFIDUNDINDNAMEP", length = 50)),
			@AttributeOverride(name = "mifidundindnameesma", column = @Column(name = "MIFIDUNDINDNAMEESMA", length = 50)),
			@AttributeOverride(name = "mifidundindnameesmacf", column = @Column(name = "MIFIDUNDINDNAMEESMACF", length = 50)),
			@AttributeOverride(name = "mifidundindnameesmap", column = @Column(name = "MIFIDUNDINDNAMEESMAP", length = 50)),
			@AttributeOverride(name = "mifidundindtermesma", column = @Column(name = "MIFIDUNDINDTERMESMA", length = 50)),
			@AttributeOverride(name = "mifidundindtermesmacf", column = @Column(name = "MIFIDUNDINDTERMESMACF", length = 50)),
			@AttributeOverride(name = "mifidundindtermesmap", column = @Column(name = "MIFIDUNDINDTERMESMAP", length = 50)),
			@AttributeOverride(name = "mifidundtype", column = @Column(name = "MIFIDUNDTYPE", length = 50)),
			@AttributeOverride(name = "mifidundtypecf", column = @Column(name = "MIFIDUNDTYPECF", length = 50)),
			@AttributeOverride(name = "mifidundtypep", column = @Column(name = "MIFIDUNDTYPEP", length = 50)),
			@AttributeOverride(name = "mifiridentifier", column = @Column(name = "MIFIRIDENTIFIER", length = 50)),
			@AttributeOverride(name = "mifiridentifiercf", column = @Column(name = "MIFIRIDENTIFIERCF", length = 50)),
			@AttributeOverride(name = "mifiridentifierp", column = @Column(name = "MIFIRIDENTIFIERP", length = 50)),
			@AttributeOverride(name = "mindenomination", column = @Column(name = "MINDENOMINATION", length = 50)),
			@AttributeOverride(name = "mindenominationcf", column = @Column(name = "MINDENOMINATIONCF", length = 50)),
			@AttributeOverride(name = "mindenominationp", column = @Column(name = "MINDENOMINATIONP", length = 50)),
			@AttributeOverride(name = "ncaavdailyturnover", column = @Column(name = "NCAAVDAILYTURNOVER", length = 50)),
			@AttributeOverride(name = "ncaavdailyturnovercf", column = @Column(name = "NCAAVDAILYTURNOVERCF", length = 50)),
			@AttributeOverride(name = "ncaavdailyturnoverp", column = @Column(name = "NCAAVDAILYTURNOVERP", length = 50)),
			@AttributeOverride(name = "ncaavdailyturncurcode", column = @Column(name = "NCAAVDAILYTURNCURCODE", length = 50)),
			@AttributeOverride(name = "ncaavdailyturncurcodecf", column = @Column(name = "NCAAVDAILYTURNCURCODECF", length = 50)),
			@AttributeOverride(name = "ncaavdailyturncurcodep", column = @Column(name = "NCAAVDAILYTURNCURCODEP", length = 50)),
			@AttributeOverride(name = "ncafreefl", column = @Column(name = "NCAFREEFL", length = 50)),
			@AttributeOverride(name = "ncafreeflcf", column = @Column(name = "NCAFREEFLCF", length = 50)),
			@AttributeOverride(name = "ncafreeflp", column = @Column(name = "NCAFREEFLP", length = 50)),
			@AttributeOverride(name = "ncafreeflcurcode", column = @Column(name = "NCAFREEFLCURCODE", length = 50)),
			@AttributeOverride(name = "ncafreeflcurcodecf", column = @Column(name = "NCAFREEFLCURCODECF", length = 50)),
			@AttributeOverride(name = "ncafreeflcurcodep", column = @Column(name = "NCAFREEFLCURCODEP", length = 50)),
			@AttributeOverride(name = "notionalcuresma", column = @Column(name = "NOTIONALCURESMA", length = 50)),
			@AttributeOverride(name = "notionalcuresmacf", column = @Column(name = "NOTIONALCURESMACF", length = 50)),
			@AttributeOverride(name = "notionalcuresmap", column = @Column(name = "NOTIONALCURESMAP", length = 50)),
			@AttributeOverride(name = "optionroot", column = @Column(name = "OPTIONROOT", length = 50)),
			@AttributeOverride(name = "optionrootcf", column = @Column(name = "OPTIONROOTCF", length = 50)),
			@AttributeOverride(name = "optionrootp", column = @Column(name = "OPTIONROOTP", length = 50)),
			@AttributeOverride(name = "placeholder", column = @Column(name = "PLACEHOLDER", length = 50)),
			@AttributeOverride(name = "pricemultiplieresma", column = @Column(name = "PRICEMULTIPLIERESMA", length = 50)),
			@AttributeOverride(name = "pricemultiplieresmacf", column = @Column(name = "PRICEMULTIPLIERESMACF", length = 50)),
			@AttributeOverride(name = "pricemultiplieresmap", column = @Column(name = "PRICEMULTIPLIERESMAP", length = 50)),
			@AttributeOverride(name = "prtrmaquote", column = @Column(name = "PRTRMAQUOTE", length = 50)),
			@AttributeOverride(name = "prtrmaquotecf", column = @Column(name = "PRTRMAQUOTECF", length = 50)),
			@AttributeOverride(name = "prtrmaquotep", column = @Column(name = "PRTRMAQUOTEP", length = 50)),
			@AttributeOverride(name = "quotepermid", column = @Column(name = "QUOTEPERMID", length = 50)),
			@AttributeOverride(name = "quotepermidcf", column = @Column(name = "QUOTEPERMIDCF", length = 50)),
			@AttributeOverride(name = "quotepermidp", column = @Column(name = "QUOTEPERMIDP", length = 50)),
			@AttributeOverride(name = "reqfattbyissuer", column = @Column(name = "REQFATTBYISSUER", length = 50)),
			@AttributeOverride(name = "reqfattbyissuercf", column = @Column(name = "REQFATTBYISSUERCF", length = 50)),
			@AttributeOverride(name = "reqfattbyissuerp", column = @Column(name = "REQFATTBYISSUERP", length = 50)),
			@AttributeOverride(name = "reqfattbyissueresma", column = @Column(name = "REQFATTBYISSUERESMA", length = 50)),
			@AttributeOverride(name = "reqfattbyissueresmacf", column = @Column(name = "REQFATTBYISSUERESMACF", length = 50)),
			@AttributeOverride(name = "reqfattbyissueresmap", column = @Column(name = "REQFATTBYISSUERESMAP", length = 50)),
			@AttributeOverride(name = "securitydescription", column = @Column(name = "SECURITYDESCRIPTION", length = 50)),
			@AttributeOverride(name = "securitydescriptioncf", column = @Column(name = "SECURITYDESCRIPTIONCF", length = 50)),
			@AttributeOverride(name = "securitydescriptionp", column = @Column(name = "SECURITYDESCRIPTIONP", length = 50)),
			@AttributeOverride(name = "strikepriceesma", column = @Column(name = "STRIKEPRICEESMA", length = 50)),
			@AttributeOverride(name = "strikepriceesmacf", column = @Column(name = "STRIKEPRICEESMACF", length = 50)),
			@AttributeOverride(name = "strikepriceesmap", column = @Column(name = "STRIKEPRICEESMAP", length = 50)),
			@AttributeOverride(name = "strikepricecuresma", column = @Column(name = "STRIKEPRICECURESMA", length = 50)),
			@AttributeOverride(name = "strikepricecuresmacf", column = @Column(name = "STRIKEPRICECURESMACF", length = 50)),
			@AttributeOverride(name = "strikepricecuresmap", column = @Column(name = "STRIKEPRICECURESMAP", length = 50)),
			@AttributeOverride(name = "suscategoryesma", column = @Column(name = "SUSCATEGORYESMA", length = 50)),
			@AttributeOverride(name = "suscategoryesmacf", column = @Column(name = "SUSCATEGORYESMACF", length = 50)),
			@AttributeOverride(name = "suscategoryesmap", column = @Column(name = "SUSCATEGORYESMAP", length = 50)),
			@AttributeOverride(name = "susendedonesma", column = @Column(name = "SUSENDEDONESMA", length = 50)),
			@AttributeOverride(name = "susendedonesmacf", column = @Column(name = "SUSENDEDONESMACF", length = 50)),
			@AttributeOverride(name = "susendedonesmap", column = @Column(name = "SUSENDEDONESMAP", length = 50)),
			@AttributeOverride(name = "susongoingesma", column = @Column(name = "SUSONGOINGESMA", length = 50)),
			@AttributeOverride(name = "susongoingesmacf", column = @Column(name = "SUSONGOINGESMACF", length = 50)),
			@AttributeOverride(name = "susongoingesmap", column = @Column(name = "SUSONGOINGESMAP", length = 50)),
			@AttributeOverride(name = "susratesma", column = @Column(name = "SUSRATESMA", length = 50)),
			@AttributeOverride(name = "susratesmacf", column = @Column(name = "SUSRATESMACF", length = 50)),
			@AttributeOverride(name = "susratesmap", column = @Column(name = "SUSRATESMAP", length = 50)),
			@AttributeOverride(name = "susstonesma", column = @Column(name = "SUSSTONESMA", length = 50)),
			@AttributeOverride(name = "susstonesmacf", column = @Column(name = "SUSSTONESMACF", length = 50)),
			@AttributeOverride(name = "susstonesmap", column = @Column(name = "SUSSTONESMAP", length = 50)),
			@AttributeOverride(name = "ttlamissued", column = @Column(name = "TTLAMISSUED", length = 50)),
			@AttributeOverride(name = "ttlamissuedcf", column = @Column(name = "TTLAMISSUEDCF", length = 50)),
			@AttributeOverride(name = "ttlamissuedp", column = @Column(name = "TTLAMISSUEDP", length = 50)),
			@AttributeOverride(name = "ttleutu12moesma", column = @Column(name = "TTLEUTU12MOESMA", length = 50)),
			@AttributeOverride(name = "ttleutu12moesmacf", column = @Column(name = "TTLEUTU12MOESMACF", length = 50)),
			@AttributeOverride(name = "ttleutu12moesmap", column = @Column(name = "TTLEUTU12MOESMAP", length = 50)),
			@AttributeOverride(name = "ttleuvl12moesma", column = @Column(name = "TTLEUVL12MOESMA", length = 50)),
			@AttributeOverride(name = "ttleuvl12moesmacf", column = @Column(name = "TTLEUVL12MOESMACF", length = 50)),
			@AttributeOverride(name = "ttleuvl12moesmap", column = @Column(name = "TTLEUVL12MOESMAP", length = 50)),
			@AttributeOverride(name = "undeeaelig", column = @Column(name = "UNDEEAELIG", length = 50)),
			@AttributeOverride(name = "undeeaeligcf", column = @Column(name = "UNDEEAELIGCF", length = 50)),
			@AttributeOverride(name = "undeeaeligp", column = @Column(name = "UNDEEAELIGP", length = 50)),
			@AttributeOverride(name = "undisin", column = @Column(name = "UNDISIN", length = 50)),
			@AttributeOverride(name = "undisincf", column = @Column(name = "UNDISINCF", length = 50)),
			@AttributeOverride(name = "undisinp", column = @Column(name = "UNDISINP", length = 50)),
			@AttributeOverride(name = "undisinesma", column = @Column(name = "UNDISINESMA", length = 50)),
			@AttributeOverride(name = "undisinesmacf", column = @Column(name = "UNDISINESMACF", length = 50)),
			@AttributeOverride(name = "undisinesmap", column = @Column(name = "UNDISINESMAP", length = 50)) })
	public XrefXxDspId getId() {
		return this.id;
	}

	public void setId(XrefXxDspId id) {
		this.id = id;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("[id=");
		builder.append(id);
		builder.append("]");
		return builder.toString();
	}

}
